### ISSUE TITLE
Windows and linux binaries have different version suffixes

### ISSUE THREAD

**Issue by soerenmuehlbauer** [microsoft/icu#122]
We plan to use System.Globalization.AppLocalIcu with a framework dependent build. That means we can only define this switch once. But as the windows binaries just have the major version as a suffix (file names) and the linux ones have the full version as a suffix, we are not able to use System.Globalization.AppLocalIcu. 

The linux release from https://github.com/unicode-org/icu/releases/tag/release-71-1 names the ".so" eg libicuuc.so.71 

Any hints?

**Comment by rp9-next** [comment]
@tarekgh Could you help with this ?

**Comment by tarekgh** [comment]
@soerenmuehlbauer You should be able to use the full ICU version and that should work on both Windows and Linux.  Here is some example:

```Xml
  <ItemGroup>
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.9" />
  </ItemGroup>
```

**Comment by soerenmuehlbauer** [comment]
@rp9-next works perfectly! Thank you
