### ISSUE TITLE
Why is 72.1.0.1 described as "internal implementation package" and fails at runtime?

### ISSUE THREAD

**Issue by cmeeren** [microsoft/icu#139]
I recently updated Microsoft.ICU.ICU4C.Runtime from 68.2.0.9 to 72.1.0.1, but my apps then started failing at startup:

```
Process terminated. Failed to load app-local ICU: icuuc68.2.0.9.dll
   at System.Environment.FailFast(System.String)
   <rest of stack trace omitted>
```

I checked the NuGet page, and see that the 72 version is described as internal and not for direct dependency:

<img width="649" alt="image" src="https://github.com/microsoft/icu/assets/7766733/0071992e-48d6-4a63-b5bb-6bedd227ef2f">

This surprised me, because the previous version is described as "mature" and "widely used":

<img width="651" alt="image" src="https://github.com/microsoft/icu/assets/7766733/e991479d-aa8b-4ff6-90e8-09ff057b7d83">

Did the nature of Microsoft.ICU.ICU4C.Runtime change? Are we supposed to just never upgrade from 68.2.0.9?

**Comment by gregor-tusar-sowa** [comment]
Why is it marked as Latest stable and not as prerelease on Nuget? 
<img width="1030" alt="image" src="https://github.com/microsoft/icu/assets/80673797/82aae910-7916-4419-b9b4-342299c27992">

**Comment by americanslon** [comment]
Also getting failure at runtime 
![image](https://github.com/microsoft/icu/assets/10237524/69c40b3e-a74a-4cc2-95e1-701f5cea860f)

**Comment by kandaker** [comment]
I get the same exception as @americanslon after upgrading to the most recent ICU nuget package. Rolling back.

**Comment by cmeeren** [comment]
Sorry, my bad. I forgot to update the version number in

```csproj
<RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="72.1.0.2" />
```

When this matches the version number in

```csproj
<PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="72.1.0.2" />
```

then it works. At least for 72.1.0.2; haven't re-tested with .1 but the error I got was the same before I matched the version numbers.

**Comment by elizabeth-quintero-nexer** [comment]
I was facing the same problem until I came here to check the previously reported issues. Is there a way to automatically update the **RuntimeHostConfigurationOption** along with the nuget package upgrade to avoid this problem in future releases?
