### ISSUE TITLE
ICU 68

### ISSUE THREAD

**Issue by EgorBo** [microsoft/icu#44]
Hello,
Is there any plan to update to ICU 68 (was released a few weeks ago)
http://site.icu-project.org/download/68

Our dotnet/icu fork depends on microsoft/icu.

**Comment by jefgen** [comment]
Hello,

Yes, our current schedule/plan is to do the update to ICU 68 in the Nov./Dec. time frame. (ICU 68 was just released on Oct. 28).
(FWIW, generally the more time consuming part of the update is reviewing the data for the CLDR update).

The internal item tracking this work is here:
https://microsoft.visualstudio.com/OS/_workitems/edit/25188398
(In case you want to "follow" it and/or add a dependency to it).

**Comment by jefgen** [comment]
Hello,

Sorry for the delay in updating.

We've just tagged the first ICU 68.2 release for MS-ICU here:
https://github.com/microsoft/icu/releases/tag/v68.2.0.1

There is also a new maintenance branch created for version 68 here as well:
https://github.com/microsoft/icu/tree/maint/maint-68

There might be a few additional commits in the future for some data related changes, but they will be merged into the `maint/maint-68` branch as needed. 

Thanks!
