### ISSUE TITLE
Windows cultures missing in ICU

### ISSUE THREAD

**Issue by PatrikMazanek** [microsoft/icu#64]
Hi,
there is wast amount of cultures which are present on Windows 10 and are missing in ICU. What are your plans on getting these two list the same?

**Comment by jefgen** [comment]
Thanks for filing an issue.
Could you please clarify which cultures on Windows 10 you are referring to, that are missing?
Thanks!

**Comment by PatrikMazanek** [comment]
Hi,
this is what I found so far:
   {
      "LanguageCode": "bin",
      "EnglishName": "Edo"
    },
    {
      "LanguageCode": "bin-NG",
      "EnglishName": "Edo (Nigeria)"
    },
    {
      "LanguageCode": "bm-Latn",
      "EnglishName": "Bamanankan (Latin)"
    },
    {
      "LanguageCode": "ca-ES-valencia",
      "EnglishName": "Valencian (Spain)"
    },
    {
      "LanguageCode": "chr-Cher",
      "EnglishName": "Cherokee (Cherokee)"
    },
    {
      "LanguageCode": "en-029",
      "EnglishName": "English (Caribbean)"
    },
    {
      "LanguageCode": "en-ID",
      "EnglishName": "English (Indonesia)"
    },
    {
      "LanguageCode": "fr-029",
      "EnglishName": "French (Caribbean)"
    },
    {
      "LanguageCode": "ha-Latn",
      "EnglishName": "Hausa (Latin)"
    },
    {
      "LanguageCode": "ibb",
      "EnglishName": "Ibibio"
    },
    {
      "LanguageCode": "ibb-NG",
      "EnglishName": "Ibibio (Nigeria)"
    },
    {
      "LanguageCode": "iu-Cans",
      "EnglishName": "Inuktitut (Syllabics)"
    },
    {
      "LanguageCode": "iu-Cans-CA",
      "EnglishName": "Inuktitut (Syllabics, Canada)"
    },
    {
      "LanguageCode": "jv-Java",
      "EnglishName": "Javanese (Javanese)"
    },
    {
      "LanguageCode": "jv-Java-ID",
      "EnglishName": "Javanese (Javanese, Indonesia)"
    },
    {
      "LanguageCode": "jv-Latn",
      "EnglishName": "Javanese (Latin)"
    },
    {
      "LanguageCode": "kr",
      "EnglishName": "Kanuri"
    },
    {
      "LanguageCode": "ks-Deva",
      "EnglishName": "Kashmiri (Devanagari)"
    },
    {
      "LanguageCode": "ks-Deva-IN",
      "EnglishName": "Kashmiri (Devanagari, India)"
    },
    {
      "LanguageCode": "ku-Arab",
      "EnglishName": "Central Kurdish (Arabic)"
    },
    {
      "LanguageCode": "la",
      "EnglishName": "Latin"
    },
    {
      "LanguageCode": "la-001",
      "EnglishName": "Latin (World)"
    },
    {
      "LanguageCode": "mn-Cyrl",
      "EnglishName": "Mongolian (Cyrillic)"
    },
    {
      "LanguageCode": "mni-IN",
      "EnglishName": "Manipuri (India)"
    },
    {
      "LanguageCode": "no",
      "EnglishName": "Norwegian"
    },
    {
      "LanguageCode": "pap",
      "EnglishName": "Papiamento"
    },
    {
      "LanguageCode": "pap-029",
      "EnglishName": "Papiamento (Caribbean)"
    },
    {
      "LanguageCode": "prs",
      "EnglishName": "Dari"
    },
    {
      "LanguageCode": "quc-Latn",
      "EnglishName": "K'iche' (Latin)"
    },
    {
      "LanguageCode": "quc-Latn-GT",
      "EnglishName": "K'iche' (Latin, Guatemala)"
    },
    {
      "LanguageCode": "sn-Latn",
      "EnglishName": "Shona (Latin)"
    },
    {
      "LanguageCode": "tg-Cyrl",
      "EnglishName": "Tajik (Cyrillic)"
    },
    {
      "LanguageCode": "tzm-Arab",
      "EnglishName": "Central Atlas Tamazight (Arabic)"
    },
    {
      "LanguageCode": "tzm-Arab-MA",
      "EnglishName": "Central Atlas Tamazight (Arabic, Morocco)"
    },
    {
      "LanguageCode": "tzm-Latn",
      "EnglishName": "Tamazight (Latin)"
    },
    {
      "LanguageCode": "tzm-Latn-DZ",
      "EnglishName": "Tamazight (Latin, Algeria)"
    },
    {
      "LanguageCode": "tzm-Tfng",
      "EnglishName": "Central Atlas Tamazight (Tifinagh)"
    },
    {
      "LanguageCode": "tzm-Tfng-MA",
      "EnglishName": "Central Atlas Tamazight (Tifinagh, Morocco)"
    },
    {
      "LanguageCode": "zgh-Tfng",
      "EnglishName": "Standard Morrocan Tamazight (Tifinagh)"
    },

Regards,
Patrik

**Comment by jefgen** [comment]
Thanks for the reply!

I looked over your list and I noticed that that there are some culture/locales that you have listed which actually are present in MS-ICU. Some of the ones listed have aliases in place (in both NLS and in ICU), so I wonder if perhaps that might be causing some issues.

For example, the following locales are present and/or have data in MS-ICU:
- chr-Cher (The CLDR/ICU locale name omits the script, so this is the same as: https://github.com/microsoft/icu/blob/master/icu/icu4c/source/data/locales/chr.txt)
- ha-Latn (The CLDR/ICU locale name omits the script, so this is the same as: https://github.com/microsoft/icu/blob/master/icu/icu4c/source/data/locales/ha.txt)
- iu-Cans-* (The CLDR/ICU locale name omits the script. There is an explicit alias setup here: https://github.com/microsoft/icu/blob/master/icu/tools/cldr/cldr-to-icu/build-icu-data.xml#L173)
- jv-Latn-* (The CLDR/ICU locale name omits the script. There is an explicit alias setup here: https://github.com/microsoft/icu/blob/master/icu/tools/cldr/cldr-to-icu/build-icu-data.xml#L178)
- ku-Arab (This one is more complicated, as the NLS locale name is different. See: https://github.com/microsoft/icu/blob/master/icu/tools/cldr/cldr-to-icu/build-icu-data.xml#L179)
- mn-Cyrl (The CLDR/ICU locale name omits the script, so this is the same as: https://github.com/microsoft/icu/blob/master/icu/icu4c/source/data/locales/mn.txt)
- mni-IN (Aliased with mni-Beng-IN. See: https://github.com/microsoft/icu/blob/master/icu/icu4c/source/data/locales/mni_IN.txt)
- no (Aliased with nb. See: https://github.com/microsoft/icu/blob/master/icu/icu4c/source/data/locales/no.txt)
- prs (Aliased with fa_AF. See https://github.com/microsoft/icu/blob/master/icu/icu4c/source/data/locales/prs.txt and https://github.com/microsoft/icu/blob/master/icu/tools/cldr/cldr-to-icu/build-icu-data.xml#L332)
- quc-* (The CLDR/ICU locale name omits the script. See: https://github.com/microsoft/icu/blob/master/icu/icu4c/source/data/locales/quc.txt)
- sn-Latn (The CLDR/ICU locale name omits the script. See: https://github.com/microsoft/icu/blob/master/icu/icu4c/source/data/locales/sn.txt)
- tg-Cyrl (The CLDR/ICU locale name omits the script. See: https://github.com/microsoft/icu/blob/master/icu/icu4c/source/data/locales/tg.txt)
- zgh-Tfng (The CLDR/ICU locale name omits the script. See: https://github.com/microsoft/icu/blob/master/icu/icu4c/source/data/locales/zgh.txt)

For some, while there is no explicit locale data, fallback will work in some cases. For example:
- ca-ES-valencia
- en-029
- en-ID
- fr-029 

I’m curious how you generated the list though?

Was the list generated by a program that dumped out all the locales from NLS and ICU?

Or was this perhaps from some customer reported issues, perhaps where a program attempted to use some of these locales and ran into issues? I think it would be good to better understand your use case and/or scenario for this.

Thanks!

**Comment by PatrikMazanek** [comment]
The list was generated by running following code on top of mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-1909 
`GetCultures([System.Globalization.CultureTypes]::AllCultures)`

With this, extra cultures are found when using the NLS comparing if we use the ICU.

Note - we were able to reproduce same on Windows installed from "Windows Server 2019 (updated Jan 2021) (x64) - DVD (English)" - version 10.0.17763.0

As for use, we have a list of supported languages which works by getting all installed cultures from the system, and we also store the language code for these languages internally. In order for us to switch to a new approach using the ICU we need to get parity on the languages available.

**Comment by PatrikMazanek** [comment]
Dear Jeff, 
did you get a chance to look into the missing languages?
Regards
Patrik

**Comment by jefgen** [comment]
Hello!

Sorry for the delay in getting back to this... Thank you kindly for the information on how you generated/obtained the list of locales.

In order to better examine the differences, I created a program that lists out all the locales in NLS and MS-ICU and used that to diff the lists in order to see what is missing in MS-ICU vs NLS.

Note: For ICU with .NET Core, the list of ICU locales is [obtained](https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/Native/Unix/System.Globalization.Native/pal_locale.c#L146) via `uloc_countAvailable` and `uloc_getAvailable`.
For NLS with .NET, the list of is [obtained](https://github.com/dotnet/runtime/blob/0817e748b7698bef1e812fd74c8a3558b7f86421/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Nls.cs#L460
) via `EnumSystemLocalesEx` with the flags `LOCALE_NEUTRALDATA | LOCALE_SPECIFICDATA`.

I've uploaded an annotated diff of the locale lists here:
https://gist.github.com/jefgen/fee0eb88560f55993b90de72a3e250e9

It turns out that there are only 13 missing locales in MS-ICU compared to NLS.

The good news is that we have work planned to add these missing locales to MS-ICU in the near future.

This will mean that all of the locales in NLS will be present in MS-ICU as well -- though they might use different names with aliases.

The locale names used by MS-ICU will potentially be different than NLS though, as the data for it comes from the upstream ICU project, which in turn gets its data from the CLDR project. The CLDR locale names are sometimes different than the NLS locale names for a variety of reasons. There will never be an exact 100% alignment between the two locale lists, as some locale names will differ due to omitted scripts, or different language codes used by CLDR. (For example: ha-Latn-GH in NLS vs ha_GH in CLDR/ICU). We add aliases where the locale names are different, so that if a program uses an NLS style name with MS-ICU, it should still work though.

**Comment by PatrikMazanek** [comment]
Hi Jeff,
That is really good news, once this is implemented, could you please update here?
Regards
Patrik

**Comment by jefgen** [comment]
> Hi Jeff,
> That is really good news, once this is implemented, could you please update here?
> Regards
> Patrik

Hello!

I wanted to update this issue to let you know that this is now implemented.

There is a new released (v68.2.0.6) tagged that includes these new/additional locales from the NLS locale data in MS-ICU. 
Link: https://github.com/microsoft/icu/releases/tag/v68.2.0.6

Please let me know if you find any more issues.

Thanks!

**Comment by PatrikMazanek** [comment]
Hi @jefgen 
I was testing with V68.2.0.9 and it seems that most of the languages are still missing - basically all you mentioned in  https://github.com/microsoft/icu/releases/tag/v68.2.0.6
Am I doing something wrong? Can you see them correctly?
Thanks a lot
Patrik

**Comment by PatrikMazanek** [comment]
Actually, please ignore my last question - I was not using the right version of the ICU assembly

**Comment by jefgen** [comment]
Hi Patrik,
Thanks for testing this out! Let me know if you run into any issues.
Thanks,
Jeff

**Comment by PatrikMazanek** [comment]
Hi Jeff,
one last question, is there any plan for the extra languages which you introduced into your ICU fork to get to main ICU/CDLR distro?
Regards
Patrik

**Comment by jefgen** [comment]
Hi Patrik,
Yes, there are some discussion/plans to contribute upstream some of these added languages back to CLDR.
However, they would initially only be added as "seed" locales, so they likely wouldn't be included in ICU until more data is contributed to them, and they can become "main" locales. (By default, ICU only takes locales from the CLDR main).
So it might take a while before they would be in the upstream ICU. Hope this gives some more context.
Thanks,
Jeff

**Comment by PatrikMazanek** [comment]
Hi,
yes it does - still need to understand the CLDR process bit more as we have some requirements for new locales as well.
Patrik
