### ISSUE TITLE
Pick up CLDR windows time zone mapping changes for South Sudan (Juba)

### ISSUE THREAD

**Issue by jefgen** [microsoft/icu#90]
Thanks to Matt Johnson-Pint for filing the upstream CLDR ticket and creating a PR.

Upstream PR: https://github.com/unicode-org/cldr/pull/1193
Upstream CLDR ticket: https://unicode-org.atlassian.net/browse/CLDR-14653

From the CLDR ticket:
Windows Update released 2021-03-29 added a new time zone "South Sudan Standard Time" which needs to be mapped to "Africa/Juba" in the windowsZones.xml file.

Once this is accepted and merged we should cherry-pick the change into MS-ICU.

**Comment by daniel-ju** [comment]
This has been resolved by #102.
